// <auto-generated />
using Facturacion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Facturacion.Migrations
{
    [DbContext(typeof(FacturacionDbContext))]
    partial class FacturacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Facturacion.Models.Articulo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Estado")
                        .HasColumnType("int");

                    b.Property<double>("Precio_Unitario")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ID_Estado");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("Facturacion.Models.Estado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Facturacion.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Vendedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Vendedor")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Facturacion.Models.Vendedor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porc_Comision")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Estado");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Facturacion.Models.Articulo", b =>
                {
                    b.HasOne("Facturacion.Models.Estado", "Estado")
                        .WithMany("Articulos")
                        .HasForeignKey("ID_Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Models.Usuario", b =>
                {
                    b.HasOne("Facturacion.Models.Vendedor", "Vendedor")
                        .WithOne("Usuario")
                        .HasForeignKey("Facturacion.Models.Usuario", "ID_Vendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Facturacion.Models.Vendedor", b =>
                {
                    b.HasOne("Facturacion.Models.Estado", "Estado")
                        .WithMany("Vendedores")
                        .HasForeignKey("ID_Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
